In [14]:
import numpy as np

# Q1

Statement: Given a 3D NumPy array arr of shape (2, 3, 4), write a code snippet to calculate the sum of all elements in the array.

Sample Input:

In [15]:
arr = np.array([[[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]],
                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

# sample output: 162

# Q2

Statement: Write a NumPy code snippet to create a 4D array arr of shape (2, 3, 4, 5) filled with random integers ranging from 0 to 9.

Sample Output:

In [16]:
arr = np.array([[[[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0],
                  [1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0]],
                 [[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0],
                  [1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0]],
                 [[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0],
                  [1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0]]],
                [[[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0],
                  [1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0]],
                 [[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0],
                  [1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0]],
                 [[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0],
                  [1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0]]]])


# Q3

Statement: Given a 4D NumPy array arr of shape (2, 3, 4, 5), write a code snippet to calculate the mean along the second axis.

Sample Input:

In [17]:
arr = np.array([[[[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0],
                  [1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0]],
                 [[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0],
                  [1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0]],
                 [[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0],
                  [1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0]]],
                [[[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0],
                  [1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0]],
                 [[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0],
                  [1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0]],
                 [[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0],
                  [1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0]]]])


sample output

    array([[[3., 4., 5., 6., 2.],
        [3., 4., 5., 6., 2.],
        [3., 4., 5., 6., 2.]],

       [[3., 4., 5., 6., 2.],
        [3., 4., 5., 6., 2.],
        [3., 4., 5., 6., 2.]]])

# Q4

Statement: You have collected data from a temperature sensor placed at different locations over a period of time. The recorded temperatures are stored in a 3D NumPy array temps of shape (7, 24, 60), where the dimensions represent the number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the average temperature for each day.

Sample Input:

In [18]:
temps = np.random.uniform(20, 30, size=(7, 24, 60))


Sample Output:

array([27.43864059, 26.99643944, 27.10398301, 27.43854821, 26.81072977,
       26.76581481, 27.07946152])

# Q5

Statement: You have collected data from multiple sensors placed in different rooms of a building. The sensor readings are stored in a 4D NumPy array readings of shape (4, 7, 24, 60), where the dimensions represent the number of sensors, number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the maximum reading for each sensor across all days.

In [19]:
readings = np.random.uniform(0, 100, size=(4, 7, 24, 60))

sample output

    array([[[89.88897518, 99.99682854, 98.19981421, 99.40158174, ... ],
            [98.70094742, 95.39951638, 99.50168002, 96.82372648, ... ],
            ...
            [93.46395392, 99.87243731, 99.09810046, 98.38483756, ... ]],

           ...

           [[94.26820117, 96.70415288, 93.48840635, 99.19723072, ... ],
            [99.78681615, 99.72712071, 97.34898231, 96.91537692, ... ],
            ...
            [98.20187725, 99.08541701, 94.79835262, 99.10678603, ... ]]])


# Q6

Statement: You have collected data from a 3D printer that measures the dimensions of printed objects. The recorded dimensions are stored in a 3D NumPy array dimensions of shape (100, 50, 3), where the dimensions represent the number of printed objects, number of measurements for each object, and the three dimensions (length, width, height), respectively. Write a code snippet to calculate the average length, width, and height across all objects.

Sample Inpumt:

In [20]:
dimensions = np.random.uniform(1, 10, size=(100, 50, 3))


Sample Output:

    array([4.99825313, 4.99388198, 5.00162036])

# Q7

Statement: You are given a 3D NumPy array data of shape (5, 6, 7) representing the sensor readings from multiple sensors placed in different locations over a period of time. Each sensor provides measurements at different time points. Write a code snippet to calculate the following statistics for each sensor:

Total number of measurements

Average measurement value

Standard deviation of measurements

Minimum measurement value

Maximum measurement value

Sample Input:

In [21]:
data = np.random.normal(0, 1, size=(5, 6, 7))


array([[[ 0.49201792,  0.1398731 , -1.22360891,  0.68220125, ..., -0.66727106],  
        [ 0.03087228, -1.28243699, -0.31224707, -0.14677595, ..., -1.79206518],  
        ...  
        [ 0.56072784,  0.24393479, -0.94418075, -1.58076437, ..., -0.13282093]]])  

Sensor 1:  
Total measurements: 42  
Average measurement: -0.038  
Standard deviation: 0.961  
Minimum measurement: -2.401  
Maximum measurement: 1.793  

Sensor 2:  
Total measurements: 42  
Average measurement: 0.059  
Standard deviation: 0.980  
Minimum measurement: -2.504  
Maximum measurement: 1.616  

...

Sensor 5:  
Total measurements: 42  
Average measurement: -0.043  
Standard deviation: 1.038  
Minimum measurement: -2.277  
Maximum measurement: 1.852  
